### ISSUE TITLE
Bot not showing candys in the bot information

### ISSUE THREAD

**Issue by DracoSchwarz** [Lunat1q/Catchem-PoGo#1539]
hello some times in the information of the bots the candy of pokemons are in 0.

**Comment by EllosGaming** [comment]
That happens with me too. Tried to refresh the pokémon list and continues 0.

**Comment by angelaayer** [comment]
I think it is a bug when transfering or catching a pokemon. It happened to me and was observing that then the candies appear.

**Comment by EllosGaming** [comment]
It happens sometimes with hatching an egg too.

**Comment by DracoSchwarz** [comment]
i watched that when i tranfer 1 duplicate of that poke the candy shows again

**Comment by Charlier69** [comment]
mee too, close the Bot and start again.

**Comment by Lunat1q** [comment]
Fixed, redownload 1.5.2.1

**Comment by hugo325** [comment]
No, unfortunately even with the 1.5.2.1 release I still have the problem.
Sometimes after a Pokémon is captured, the display of candy related to that Pokémon is not done correctly. To fix this I am forced to refresh the list of my Pokémon.
I use translation app: fr

![image](https://cloud.githubusercontent.com/assets/6458961/18348218/6abf7696-75ca-11e6-9b10-d42020a54b25.png)
